#!/bin/sh

# portron user settings dir
[ -d /home/guest/.portron ] || mkdir /home/guest/.portron

# electron homedir
[ -d /home/guest/.config ] || mkdir /home/guest/.config

# app runs as guest
chown guest:guest /home/guest
chown -R guest:guest /home/guest/.*

/opt/bin/synconfig
