#!/bin/sh
#
# Shutdown idle watcher.
# Author: T.Jokiel <http://porteus-kiosk.org>

SHUTDOWNIDLE=`grep SHUTDOWNIDLE= /etc/xdg/openbox/autostart | cut -d= -f2`

while [ 1 ]; do
    idle=$(echo `xprintidle` | sed s/...$//); [ "$idle" ] || idle=1
    if [ $idle -gt $SHUTDOWNIDLE ]; then
	dunstify -u normal -i /usr/share/icons/oxygen/22x22/status/dialog-information.png "No activity detected in last $(($SHUTDOWNIDLE/60)) minutes. System will shutdown in 5 seconds..."
	sleep 5
	idle=$(echo `xprintidle` | sed s/...$//); [ "$idle" ] || idle=1
	[ $idle -gt $SHUTDOWNIDLE ] && init 0 || sleep $(($SHUTDOWNIDLE-$idle))
    else
	sleep $(($SHUTDOWNIDLE-$idle))
    fi
done
