#!/bin/sh
#
# Standby idle watcher.
# Author: T.Jokiel <http://porteus-kiosk.org>

STANDBYIDLE=`grep STANDBYIDLE= /etc/xdg/openbox/autostart | cut -d= -f2`

while [ 1 ]; do
    idle=$(echo `xprintidle` | sed s/...$//); [ "$idle" ] || idle=1
    if [ $idle -gt $STANDBYIDLE ]; then
	dunstify -u normal -i /usr/share/icons/oxygen/22x22/status/dialog-information.png "No activity detected in last $(($STANDBYIDLE/60)) minutes. System will standby in 5 seconds..."
	sleep 5
	idle=$(echo `xprintidle` | sed s/...$//); [ "$idle" ] || idle=1
	[ $idle -gt $STANDBYIDLE ] && { xdotool key Menu; echo standby > /sys/power/state; } || sleep $(($STANDBYIDLE-$idle))
    else
	sleep $(($STANDBYIDLE-$idle))
    fi
done
