#!/bin/sh

cd /opt/setup

# wizard for runtime configuration
# requires persistent installation as writes settings only to home dir

[ -d ${NEO_CFG_ROOT} ] && {
    sh ${CMD_WIZARD_CONFIG}
    [ -f /tmp/wizard-continue ] && {

        rm -f /tmp/wizard-continue

        . wizards/lib/6-genconfig
        . /opt/bin/synconfig

        /opt/bin/reinitsound

        sync
    }
} || {
    echo "- wizard not available for live environment"
}

